"""Top-level tab indices — keep in sync with src/app.py tab_views order."""

TAB_DASHBOARD = 0
TAB_PORTFOLIO = 1
TAB_WATCHLIST = 2
TAB_STOCK_DETAIL = 3
TAB_COMPARE = 4
TAB_STRATEGY_BACKTESTS = 5
TAB_LEADERBOARD = 6
TAB_OPTIMIZATION = 7
TAB_LIVE = 8
TAB_DATA_MANAGEMENT = 9
TAB_ASSISTANT = 10
TAB_SETTINGS = 11

# Legacy aliases (update callers gradually)
TAB_SINGLE_TICKER = TAB_STOCK_DETAIL
TAB_RESEARCH_UNIVERSE = TAB_DATA_MANAGEMENT
TAB_DATA_INGEST = TAB_DATA_MANAGEMENT
